### ISSUE TITLE
upgrade old surveyors to un-stick contributions

### ISSUE THREAD

**Issue by evq** [brave-intl/bat-ledger#105]
currently we have a number of ledger clients stuck using old surveyors instead of the current one. it seems most likely that this is caused by https://github.com/brave-intl/bat-client/issues/35 in combination with the fact that some clients reconcile date was not pushed back on grant claim and grants were made unredeemable before their maturity date.

we will fix the client side - to go out in a browser-laptop release but as a quick fix we should unstick clients by upgrading old surveyors servers side on demand.

**Comment by mrose17** [comment]
Made OBE by https://github.com/brave-intl/bat-client/pull/36
