### ISSUE TITLE
Fix eyeshade timestamp bug

### ISSUE THREAD

**Issue by jlbyrne** [brave-intl/bat-ledger#1093]
uploading statements causes the date inserted to be unix time 0.  We need a migration that will correct those. The created_at stamps are correct, so can just copy that. 
Then find and fix the bug which caused the inserts to use unix time 0.

**Comment by janethben88** [comment]
Kindly contact the Support team to fix the issue below is their livechat link https://direct.lc.chat/14756535/

**Comment by tsmartt** [comment]
Fixed in https://github.com/brave-intl/bat-ledger/pull/1101
