### ISSUE TITLE
eyeshade reports should be fetchable without github login for local dev

### ISSUE THREAD

**Issue by evq** [brave-intl/bat-ledger#116]

**Comment by mrose17** [comment]
in the interim, you can go to https://github.com/organizations/brave-intl/settings/applications and use the developer apps defined there, put the values in .env as $SERVICE_GITHUB_CLIENT_ID, etc.

**Comment by evq** [comment]
well, not anyone outside the org. I usually work around locally with a patch that comments out the bits that break - when I get a little bit of time I'll get things sorted more permanently.

**Comment by mrose17** [comment]
sure. or people outside the org can create their own app (that's what i've been using for development for the last two years...)

**Comment by evq** [comment]
this was fixed in c194778 which was partially rebased into #182. thanks @mmclau14
