### ISSUE TITLE
Owner accounts can't be easily deleted 

### ISSUE THREAD

**Issue by nvonpentz** [brave-intl/bat-ledger#162]
Many publishers have requested that their accounts be deleted.  We do not have an easy way to do this.  Right now we must manually delete the records from both eyeshade and publishers.  This is error prone and not scalable.

We should create some endpoint on eyeshade that publishers can hit that deletes all records associated with an owner (owner, their channels, token, etc).  Something like this would work:
```
DELETE /v2/owners/{owner}
```

Related to https://github.com/brave-intl/publishers/issues/751

**Comment by mmclau14** [comment]
@nvonpentz is this not available through: `/v1/owners/{owner}/{publisher}`?

**Comment by nvonpentz** [comment]
@mmclau14 My understanding is that a `publisher` on eyeshade is the same thing as a `channel` on publishers.  That is, a `publisher` on eyeshade represents a website or youtube or twitch channel.  I think this is a relic of the past when one publisher account could only have a single channel.

**Comment by mmclau14** [comment]
@nvonpentz ok, so just account for `n` channels and `n` tokens
Should we be allowing fine tuned control over what can be removed? aka, would you like to be sending a list of channels and a list of tokens? or just wipe it all

**Comment by mmclau14** [comment]
i suppose the other question i would have is would you like for me to try to do as many as possible and send back a resolve / rejected array for the ones i am unable to do or just do everything i can to make sure that they all happen or none of them happen

**Comment by lgebhardt** [comment]
@mmclau14 

> i suppose the other question is would you like to have as many as possible try to complete and send back a resolve / rejected array for the ones that fail or just do everything that can be done to make sure that they all happen or none of them happen.

Ideally deleting an owner should be atomic. This will give the best user experience as it prevents the odd case where only half the channels are deleted when the request was to delete the Owner account. 

> ok, so just account for n channels and n tokens

I believe tokens are only created for site channels through `PUT /v1/owners/{owner_identifier}/verify/{publisher_id}` (where `publisher_id` is the domain). Channels are set on eyeshade through `POST /v2/owners`. So there may not be n tokens for n channels, if some of the channels are youtube or twitch that do not have tokens.

> Should we be allowing fine tuned control over what can be removed? aka, would you like to be sending a list of channels and a list of tokens? or just wipe it all

Individual channels can currently be deleted with a call to `DELETE /v1/owners/{owner_identifier}/{channel_identifier}`. So I don't think fine tuned control is needed.

**Comment by nvonpentz** [comment]
@mmclau14 We also want to make sure the funds associated with each channel/owner are not removed when an owner is removed.

Suppose we have a owner `A` with a channel `a` that will be paid out 100 BAT in the next settlement.  Suppose we use this endpoint to delete `A`, then someone reverifies `a` under owner `B`.  Owner`B` should still be credited with the 100 BAT for channel `a`.

This should be the default behavior for the existing endpoint that deletes channels `/v1/owners/{owner}/{channel}`.

**Comment by mmclau14** [comment]
@nvonpentz i believe this happens if i leave the owner in the db, but wipe all of the data on the model and remove the tokens, which is what i have set up.

**Comment by evq** [comment]
As Nick previously pointed out there are considerations around previous payouts. The scenario he suggested would work fine, but there are others that do not.

It is difficult to address this properly given the current data model so I would suggest we push this off until we make some larger changes.
