### ISSUE TITLE
blacklist fraudulant publishers and do sanity check when creating report

### ISSUE THREAD

**Issue by maikelmclauflin** [brave-intl/bat-ledger#175]
blacklisting publishers currently happens manually on voting document basis
mark publisher's excluded boolean if they are registered in our blacklist
if excluded is true, do not include in payout information
take the publisher, check the blacklist, flip the bool if
```
create mongodb indeces for blacklist and query them
  eyeshade/workers/wallet.js:voting-report
    mark excluded
  eyeshade/workers/reports.js:report-publishers-contributions
    sanity check to make sure no publishers in report have
```

**Comment by mrose17** [comment]
@mmclau14 - am i correct in thinking that we want to add an `exclude` flag to the `owner` and `publisher` documents and be able to set those administratively, and then consult them when generating settlement files?

**Comment by evq** [comment]
OBE
