### ISSUE TITLE
Make code more legible and testable

### ISSUE THREAD

**Issue by maikelmclauflin** [brave-intl/bat-ledger#176]
there are a variety of improvements that could be made to make the code more legible and testable

### legible
- using imports instead of requires and filename patterns
- breaking apart monolithic files
- destructuring
- using default values

### testable
- breaking apart monolithic files
- more (and exporting existing) pure functions (where available)

these items can be addressed in any order, as well as broken up by server / worker

**Comment by mrose17** [comment]
@mmclau14 - i'd also be happier if eslint had more options to let us get the syntax use more consistent... that would also help legibility!

also, is this issue blocked until after the merge of the `extractor` branch?

**Comment by mmclau14** [comment]
yeah, i'm focusing on doing everything i can to make sure that actual needed features are completed first. I have not been doing this task specifically yet. just putting it here as a reminder that there is more to be done and keeping it in mind for how new code is written.

Happy to figure out how to use our linter to help with that process as well, though most of the "issue" is that there are too many things happening on a single, line, function, or file. which of course, a linter would not be able to help with much.
