### ISSUE TITLE
Disable propagation of channel verification from eyeshade to ledger

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/bat-ledger#219]
@evq

**Comment by mmclau14** [comment]
@yachtcaptain23 which endpoint is this? i don't see a `verified_status` in a quick search of the ledger repo

**Comment by yachtcaptain23** [comment]
Haha my mistake @maikelmclauflin . It's `verification_status`. I believe @evq will be doing a redirect to `api/channels/<id>/verification_status` on https://github.com/brave-intl/publishers/pull/853

**Comment by maikelmclauflin** [comment]
steps:
get endpoint from @yachtcaptain23 
deploy to staging for test
redirect when token is not available in eyeshade to publishers endpoint

**Comment by evq** [comment]
@maikelmclauflin what eyeshade token are you referring to?

**Comment by evq** [comment]
I changed the title to clarify this issue and cleaned up the comments

**Comment by yachtcaptain23** [comment]
Action items:

@maikelmclauflin will edit Ledger's `ledger/controllers/publisher.js#v3/identity` to fetch from the Publishers app at the endpoint `https://publishers.basicattentiontoken.org/api/channels/identity?publisher=example.com` and reply back with Publisher App's endpoint's result as a passthrough.

@yachtcaptain23 will return the same response that `ledger/controllers/publisher.js#v3/identity` previously had, which is the following:

Verified:
```
{ SLD: 'espn.com',
  RLD: '',
  QLD: '',
  publisher: 'espn.com',
  properties: {verified: true, timestamp: 1000000 } }
```

Not verified:
```
{ SLD: 'example.com',
  RLD: '',
  QLD: '',
  publisher: 'example.com',
  properties: {} }
```

Timestamp, according to the logic in `bat-ledger/node_modules/bat-publisher/index.js` seems to be when the business occurred i.e. `Time.now`.
