### ISSUE TITLE
expose endpoint to create a card of a given currency for owner

### ISSUE THREAD

**Issue by evq** [brave-intl/bat-ledger#229]
will require the `cards:write` scope

**Comment by evq** [comment]
it sounds like we will want to make it generic enough so that publishers could create cards of other currencies beyond just BAT

**Comment by maikelmclauflin** [comment]
is there anything we should be sending back to publishers (or any other service) through this endpoint? this is what i am getting back
```
{ address: { wire: 'WIRE_NUMBER' },
  available: '0.00',
  balance: '0.00',
  currency: 'BAT',
  id: 'UNIQUE_ID,
  label: 'BAT card',
  lastTransactionAt: null,
  settings: { position: UNIQUE_NUMBER, protected: false, starred: false },
  normalized: [ { available: '0.00', balance: '0.00', currency: 'USD' } ],
  wire:
   [ ACCOUNT_OBJECT, ... ] }
```

**Comment by evq** [comment]
@maikelmclauflin address might be useful, but not strictly needed

**Comment by maikelmclauflin** [comment]
alright. i'll start with just an empty object. the address doesn't seem to hold anything except a wire number which looks like something where you would send money to from a bank wire
