### ISSUE TITLE
Tests: Database should be cleaned between tests

### ISSUE THREAD

**Issue by ayumi** [brave-intl/bat-ledger#237]
To avoid unexpected interactions and allow use of fixtures, tests should clean some or all database data during setup or teardown.

**Comment by maikelmclauflin** [comment]
this can be added before the test script. `db-reset` should already exist. if it does not already on master, it is coming on another branch.

**Comment by evq** [comment]
@maikelmclauflin we can use the create-tokens bin from the `bat-go` repo to create a unique grant. https://github.com/brave-intl/bat-go/blob/master/bin/create-tokens/main.go
