### ISSUE TITLE
Possible typo in surveyor controller's initialization

### ISSUE THREAD

**Issue by Slava** [brave-intl/bat-ledger#318]
This line is supposed to ensure only one herokku dyno runs the periodic provisioning. Seems like the code also was meant to run the provisioning when the service is ran locally but the check should be `!== undefined` instead of `!== 'undefined'`. Seems like not an issue unless the code is ever tested with `process.env.DYNO` not set.

https://github.com/brave-intl/bat-ledger/blob/73f8e54676a51b4870b0ae58e0ea5daaa6eeb89c/ledger/controllers/surveyor.js#L693

**Comment by maikelmclauflin** [comment]
while i agree with you that we should not be doing the check in this manner, i don't know that it's an invalid check. this is a `typeof` check, not a value check

**Comment by Slava** [comment]
oops my bad, I didn't realize it is `typeof`
