### ISSUE TITLE
update supertest agents with valid creds

### ISSUE THREAD

**Issue by maikelmclauflin** [brave-intl/bat-ledger#384]
currently the agent is not being set up to send credentials to the servers.
https://visionmedia.github.io/superagent/#agents-for-global-state

**Comment by evq** [comment]
I'm pretty sure this is not actually an issue, wouldn't our tests fail if this were the case?

Per the above link:
> Regular request methods called on the agent will be used as defaults for all requests made by that agent.
> The complete list of methods that the agent can use to set defaults is: use, on, once, **set** ...

I think calling `set` here should be enough, no?
https://github.com/brave-intl/bat-ledger/blob/master/test/utils.js#L64

Closing for now.

**Comment by maikelmclauflin** [comment]
yes, i did not realize that the this supertest package was being used: https://github.com/brave-intl/supertest deleting branch.
