### ISSUE TITLE
create POST /v3/publishers/settlement which takes a file

### ISSUE THREAD

**Issue by evq** [brave-intl/bat-ledger#449]
see https://github.com/brave-intl/bat-ledger/blob/master/ledger/controllers/grants.js#L494 for an example of file upload

**Comment by nvonpentz** [comment]
hey @evq, what's the motivation for this? if https://github.com/brave-intl/publishers/issues/1604 is implemented to allow for file upload, would that solve this for you?

**Comment by evq** [comment]
yeah I think that would supersede this issue, let's close this
