### ISSUE TITLE
create new manual_settlement type and allow publishers to submit settled txns

### ISSUE THREAD

**Issue by evq** [brave-intl/bat-ledger#519]
will be used to track manual publisher payments as part of - https://github.com/brave-intl/publishers/issues/1571

may need to adjust auth on existing endpoint used to post settled transactions

**Comment by nvonpentz** [comment]
TODO
* Expose `POST /v2/publishers/settlement` to publishers application (do we want to remove the session auth?)
* Update settlement report logic such that if there is a entry whose type is 'manual':
    1.  Create a transaction brave wallet -> owner account that save the documentId from the entry
    2.  Create a settlement transaction owner account -> uphold that saves the documentId from the entry

Steps (i) and (ii) should be a single postgres transaction such that if either fail neither occurs.
