### ISSUE TITLE
wallet endpoint returns rates as both numerics and strings

### ISSUE THREAD

**Issue by nvonpentz** [brave-intl/bat-ledger#538]
An example from production:
```
GET /v1/owners/{owner}/wallet

{
    "rates": {
        "BCH": "0.000973962801832924",
        "BTC": "0.000035108075709779",
        "BTG": "0.011356134690481058",
        "DASH": "0.001649120353304139",
        "ETH": "0.000956931907207602",
        "EUR": "0.121169315180552025",
        "LTC": "0.002827874220204027",
        "USD": "0.137424114263916609",
        "XAU": 0.00010326872490476276,
        "XRP": "0.43256783474601873"
    },
  ...
}
```

I believe XAU should be a string.  Depending on the currencies they've added there may be more currencies  than just XAU that aren't strings.

Currently this is not a problem, but it caused problems for https://github.com/brave-intl/publishers/pull/1617#discussion_r258729443.

**Comment by maikelmclauflin** [comment]
what is this caused by exactly? want to write a test if possible

**Comment by nvonpentz** [comment]
Based on the fact that XAU (gold) was the only one that's not a string, I think this is related to the rates that uphold sends us when a publisher creates a new uphold card.

**Comment by maikelmclauflin** [comment]
cool. will test and try to replicate
