### ISSUE TITLE
open up rates to all uphold cards

### ISSUE THREAD

**Issue by maikelmclauflin** [brave-intl/bat-ledger#560]
nonstandard uphold cards can still be used for default currencies.
cards should either be restricted to a subset, or @brave-intl/bat-ratios should be updated to send back uphold rates those rates should be included in wallet requests:

https://sentry.io/organizations/brave-software/issues/783234441/?project=225116&query=is%3Aunresolved&statsPeriod=14d&utc=false

as per @corymcdonald

**Comment by corymcdonald** [comment]
If we do use a subset then we need to ensure that no user is currently using that default currency to transfer out to

**Comment by maikelmclauflin** [comment]
@evq has expressed that it makes sense to open it up to all cards.
