### ISSUE TITLE
instrument outgoing client requests to uphold and other services

### ISSUE THREAD

**Issue by evq** [brave-intl/bat-ledger#572]
see bat-go for an example:

https://github.com/brave-intl/bat-go/blob/63859ecc86d314204ce646697866ab774409c2e8/middleware/prometheus.go

**Comment by maikelmclauflin** [comment]
implemented: https://github.com/brave-intl/bat-ledger/commit/96d2f96632f6dd49dc70e09dc5eaf1baedca3361
