### ISSUE TITLE
Update to Autocontribute Amounts

### ISSUE THREAD

**Issue by alexwykoff** [brave-intl/bat-ledger#657]
**Problem Statement**
Users often cannot earn enough BAT via Ads to meet the auto-contribute default value. As such, they receive an ‘insufficient funds’ message which causes confusion and frustration. 

**Proposed Solution**
To facilitate a smoother flow, an adjustment to the autocontribution amount table and default value should occur.

The old table values were [20,30,50,85,100]. 

A heavy user of Brave Rewards with maximum Ads per day can typically earn about 20 BAT per month (maximum potential at the moment).

As such the new table is proposed : [5, 10, 15, 20, 25, 50, 100].

A new default value of 10BAT is proposed as well ($3-$4)

With this new table and new default, average-to-heavy users should be able to autocontribute [a-c] without issue. Heavy users will be able to easily tip as well.

For users who wish to buy into the system and strongly reward, that option is available as well.

There are further improvements possible to the client side as well regarding checks on actual sent amount (which differs from budget due to unverified pubs). Those will be tracked in separate issues.

**Comment by evq** [comment]
completed
