### ISSUE TITLE
Last Settlement endpoint

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/bat-ledger#883]
Marking as P2, as this is causing some users unable to view their page. [You can see the trace here](https://rpm.newrelic.com/accounts/2604309/applications/592980707_h592981222/transactions?type=app#id=5b22436f6e74726f6c6c65722f7075626c6973686572732f686f6d65222c22225d&app_trace_id=196a0680-9f50-11ea-a19b-0242ac110007_4188_10443&tab-detail_196a0680-9f50-11ea-a19b-0242ac110007_4188_10443=trace_details)

Basically we'd want to do this all on Eyeshade's side as a new endpoint:

```
      return {} if transactions.blank?
       # Find most recent settlement transaction
      last_transaction = transactions.select { |transaction|
        transaction["settlement_amount"].present?
      }.last # Eyeshade returns transactions ordered_by created_at

      return {} if last_transaction.nil?

      last_settlement_time = last_transaction["created_at"].to_time # Eyeshade returns transactions ordered_by created_at

       # Find all settlement transactions that occur within the same month as the last settlement timestamp
      last_settlement_transactions = transactions.select { |transaction|
        transaction["created_at"].to_time.at_beginning_of_month == last_settlement_time.at_beginning_of_month &&
        transaction["settlement_amount"].present?
      }

      # Sum the all the settlement transactions
      last_settlement_currency = last_settlement_transactions&.first["settlement_currency"] || nil

      # The amount is the BAT that was withdrawn from our ledger. This is a negative value.
      last_settlement_amount_bat = last_settlement_transactions.map { |transaction|
        transaction["amount"].to_d.abs
      }.reduce(:+)

      # Settlement amount will be in the user's default currency
      last_settlement_amount_currency = last_settlement_transactions.map { |transaction|
        transaction["settlement_amount"].to_d
      }.reduce(:+)

      {
        amount_bat: last_settlement_amount_bat,
        amount_currency: last_settlement_amount_currency,
        timestamp: last_settlement_time.to_i,
        currency: last_settlement_currency
      }
```

**Comment by corymcdonald** [comment]
I'd be good with keeping our Ruby code how it is, because the slow down comes with the time it takes to return all the transactions. 

It would be great if we could instead add filters for the `transactions/` endpoint, perhaps something like

`v1/accounts/:uuid/transactions?transaction_type=contribution_settlement&transaction_type=referral_settlement`

or 

`v1/accounts/:uuid/transaction/settled=true`

---

If we could get the response time under 1 second that would be ideal. Right now there's no index on transaction_type in the transactions table
