### ISSUE TITLE
move source-of-truth for publisher rules to eyeshade

### ISSUE THREAD

**Issue by mrose17** [brave-intl/bat-ledger#97]
1. Deprecate these calls in the ledger:

    GET    /v2/publisher/identity       
    GET    /v2/publisher/identity/verified

2. Move these calls from the ledger to the eyeshade server:

    POST   /v2/publisher/ruleset
    PATCH  /v2/publisher/rulesets
    PUT    /v2/publisher/ruleset/{publisher}
    DELETE /v2/publisher/ruleset/{publisher}
    GET    /v2/reports/publisher/rulesets

3. Add messages from eyeshade to ledger that provide the functionality in the five calls above.

**Comment by mmclau14** [comment]
@mrose17 do we want to `move` or copy and deprecate the old so that people using this endpoint can have time to move over? or will the 404 be enough to inform the individual at that time

**Comment by mmclau14** [comment]
1. taken care of in commit: `36f77d1a`

**Comment by mrose17** [comment]
OBE.
